print("hello princy")
print("it is  working fine")
print("finally done")
import keras
print("it should run")
print("it is running")
print('!')
print("its done")
print("hi")
print("done")
print("what to do")
print("hopefully")
print("ho jao na plsss")
print("new")
print("i think its done")
print("Its almost there")
print("finally its done")
accuracy=97.1
out=open('/deeplearning/output.html','r+')
out.read()
out.write('Accuracy achieved:' +accuracy)
out.close()